import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<main className="h-screen">
					<header className="px-[24px]
						mt-[50px]">
						<div>
							<p className="text-white">Total saved</p>
							<p className="text-white
								text-4xl
								font-bold
								mt-[6px]">$32,680.00</p>
						</div>

						<div className="mt-[30px]">
							<p className="text-white">Work time saved</p>
							<p className="text-white
								text-4xl
								font-bold
								mt-[6px]">1 month, 1 week</p>
						</div>
					</header>

					<div className="
						fixed
						bottom-0
						inset-x-0
						py-[50px]
						px-[24px]
						bg-sky-100
						h-[70vh]
						rounded-t-[30px]">
						{children}
					</div>
				</main>
			</body>
		</html>
	);
}
